apply plugin: 'com.android.library'
apply from: '../constants.gradle'

android {
    namespace 'xyz.doikki.videoplayer'
    compileSdk project.ext.compileSdkVersion
    buildToolsVersion project.ext.buildToolsVersion

    defaultConfig {
        minSdk project.ext.minSdkVersion
        targetSdk project.ext.targetSdkVersion
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    compileOnly project.ext.annotation
}

ext {
    PUBLISH_ARTIFACT_ID = 'dkplayer-java'
}

